-- Flag de cuenta monetaria
ALTER TABLE public.tab_accounts
  ADD COLUMN IF NOT EXISTS is_monetary boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.tab_accounts.is_monetary IS 'Indica si la cuenta es monetaria (sujeta a revaluación cambiaria por diferencial). Bancos, CxC y CxP en ME deben marcarse como monetarias.';

-- Marcar bancos automáticamente
UPDATE public.tab_accounts SET is_monetary = true WHERE is_bank_account = true AND is_monetary = false;

-- Tabla de corridas de revaluación
CREATE TABLE IF NOT EXISTS public.tab_fx_revaluation_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enterprise_id bigint NOT NULL,
  year integer NOT NULL,
  month integer NOT NULL,
  cutoff_date date NOT NULL,
  revaluation_type text NOT NULL DEFAULT 'UNREALIZED', -- UNREALIZED | REALIZED
  journal_entry_id bigint REFERENCES public.tab_journal_entries(id) ON DELETE SET NULL,
  total_gain numeric(18,2) NOT NULL DEFAULT 0,
  total_loss numeric(18,2) NOT NULL DEFAULT 0,
  details_json jsonb,
  status text NOT NULL DEFAULT 'POSTED', -- DRAFT | POSTED | REVERSED
  created_by uuid DEFAULT auth.uid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  reversed_at timestamptz,
  notes text
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fx_reval_runs_unique
  ON public.tab_fx_revaluation_runs (enterprise_id, year, month, revaluation_type)
  WHERE status = 'POSTED';

ALTER TABLE public.tab_fx_revaluation_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "fx_reval_runs_select" ON public.tab_fx_revaluation_runs
  FOR SELECT USING (
    is_super_admin(auth.uid()) OR user_is_linked_to_enterprise(auth.uid(), enterprise_id)
  );

CREATE POLICY "fx_reval_runs_insert" ON public.tab_fx_revaluation_runs
  FOR INSERT WITH CHECK (
    is_super_admin(auth.uid()) OR user_is_linked_to_enterprise(auth.uid(), enterprise_id)
  );

CREATE POLICY "fx_reval_runs_update" ON public.tab_fx_revaluation_runs
  FOR UPDATE USING (
    is_super_admin(auth.uid()) OR user_is_linked_to_enterprise(auth.uid(), enterprise_id)
  );

-- Función: saldo de una cuenta en moneda extranjera a una fecha (suma original_debit - original_credit por moneda)
CREATE OR REPLACE FUNCTION public.get_account_fx_balance(
  _account_id bigint,
  _currency_code text,
  _cutoff_date date
)
RETURNS numeric
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(SUM(
    COALESCE(d.original_debit, d.debit_amount, 0)
    - COALESCE(d.original_credit, d.credit_amount, 0)
  ), 0)
  FROM public.tab_journal_entry_details d
  JOIN public.tab_journal_entries j ON j.id = d.journal_entry_id
  WHERE d.account_id = _account_id
    AND j.entry_date <= _cutoff_date
    AND j.status = 'contabilizada'
    AND COALESCE(d.currency_code, j.currency_code, 'GTQ') = _currency_code;
$$;

COMMENT ON FUNCTION public.get_account_fx_balance IS 'Calcula el saldo vivo de una cuenta monetaria expresado en su moneda extranjera, sumando original_debit/credit de partidas contabilizadas hasta la fecha de corte.';