CREATE TABLE public.tab_declaration_calculations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enterprise_id bigint NOT NULL REFERENCES public.tab_enterprises(id) ON DELETE CASCADE,
  form_type text NOT NULL CHECK (form_type IN ('IVA_PEQUENO','IVA_GENERAL','ISR_MENSUAL','ISR_TRIMESTRAL','ISO_TRIMESTRAL')),
  period_month integer,
  period_year integer NOT NULL,
  inputs jsonb NOT NULL DEFAULT '{}'::jsonb,
  result jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_declaration_calc_lookup ON public.tab_declaration_calculations (enterprise_id, form_type, period_year, period_month, created_at DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.tab_declaration_calculations TO authenticated;
GRANT ALL ON public.tab_declaration_calculations TO service_role;

ALTER TABLE public.tab_declaration_calculations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage declaration calculations from their enterprises"
ON public.tab_declaration_calculations FOR ALL TO authenticated
USING (enterprise_id IN (SELECT tab_user_enterprises.enterprise_id FROM public.tab_user_enterprises WHERE tab_user_enterprises.user_id = auth.uid()))
WITH CHECK (enterprise_id IN (SELECT tab_user_enterprises.enterprise_id FROM public.tab_user_enterprises WHERE tab_user_enterprises.user_id = auth.uid()));

ALTER TABLE public.tab_tax_forms ADD COLUMN declaration_calculation_id bigint REFERENCES public.tab_declaration_calculations(id) ON DELETE SET NULL;