-- Create table for enterprise tax configuration
CREATE TABLE public.tab_enterprise_tax_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enterprise_id bigint NOT NULL,
  tax_form_type text NOT NULL, -- 'IVA_PEQUENO', 'IVA_GENERAL', 'ISR_MENSUAL', 'ISR_TRIMESTRAL'
  tax_rate numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  UNIQUE(enterprise_id, tax_form_type)
);

-- Enable RLS
ALTER TABLE public.tab_enterprise_tax_config ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view their enterprise tax config"
ON public.tab_enterprise_tax_config
FOR SELECT
USING (enterprise_id IN (
  SELECT enterprise_id FROM tab_user_enterprises WHERE user_id = auth.uid()
));

CREATE POLICY "Users can insert their enterprise tax config"
ON public.tab_enterprise_tax_config
FOR INSERT
WITH CHECK (enterprise_id IN (
  SELECT enterprise_id FROM tab_user_enterprises WHERE user_id = auth.uid()
));

CREATE POLICY "Users can update their enterprise tax config"
ON public.tab_enterprise_tax_config
FOR UPDATE
USING (enterprise_id IN (
  SELECT enterprise_id FROM tab_user_enterprises WHERE user_id = auth.uid()
));

CREATE POLICY "Users can delete their enterprise tax config"
ON public.tab_enterprise_tax_config
FOR DELETE
USING (enterprise_id IN (
  SELECT enterprise_id FROM tab_user_enterprises WHERE user_id = auth.uid()
));